### ISSUE TITLE
Dev releases are crowding out real releases

### ISSUE THREAD

**Issue by jbednar** [pyviz/pyctdev#1]
It's true that we need to release datashader, but at least for now, the dev releases are drowning out the real ones:

![image](https://user-images.githubusercontent.com/1695496/40083530-09a32c6c-585a-11e8-85db-378483c6bac1.png)

Is there a way to have the latest real release visible somehow, other than by making fewer dev releases?

**Comment by ceball** [comment]
pyviz projects can currently choose one of two schemes for getting 'pre-release' packages: either (1) push pre-release tag to have packages built, or (2) have packages built all the time from master.

For scheme 1, pushing a pre-release tag means github creates an entry in its releases page. Pushing a pre-release tag indicates you are making some kind of release, after all. I imagine most users of scheme 1 will not push so many tags between releases, so it might not be a problem. Datashader is currently set up to use this scheme. However, what's happened here is there are loads of tags because everything was being created/debugged for the first time (including pyctdev itself). Most of (all?) those tags are from a PR branch and could be deleted. 

(If for scheme 1 many dev tags in the way is actually a problem, we could maybe find a tag format that works as a python pre-release package but doesn't trigger github to detect a release?)

Meanwhile, for scheme 2, there'll be no tags, so there'll be no release entries on github corresponding to the packages. You'll get packages like `param-1.6.1.post1+gSHA` , `param-1.6.1.post2+gSHA`, etc, without tags so also without github releases.

**Comment by ceball** [comment]
(You could mix the schemes too.)

**Comment by jbednar** [comment]
Ok, sounds like it's all good; all I need to do is delete the tags that were really for debugging rather than for actually releasing something of interest to anyone. Thanks!
